import { Task, TeamMember, Project, Committee } from '@/types';

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'fac-001',
    name: 'Dr. Sarah Chen',
    email: 'sarah.chen@gjust.edu.in',
    avatar: 'SC',
    role: 'HOD',
    department: 'Computer Science',
    specialization: 'Artificial Intelligence',
    isOnline: true,
    tasksAssigned: 5,
    tasksCompleted: 23,
  },
  {
    id: 'fac-002',
    name: 'Prof. Rahul Kumar',
    email: 'rahul.kumar@gjust.edu.in',
    avatar: 'RK',
    role: 'Senior Professor',
    department: 'Computer Science',
    specialization: 'Database Systems',
    isOnline: true,
    tasksAssigned: 8,
    tasksCompleted: 31,
  },
  {
    id: 'fac-003',
    name: 'Dr. Emily Watson',
    email: 'emily.watson@gjust.edu.in',
    avatar: 'EW',
    role: 'Assistant Professor',
    department: 'Computer Science',
    specialization: 'Machine Learning',
    isOnline: false,
    tasksAssigned: 6,
    tasksCompleted: 18,
  },
  {
    id: 'fac-004',
    name: 'Prof. Amit Patel',
    email: 'amit.patel@gjust.edu.in',
    avatar: 'AP',
    role: 'Associate Professor',
    department: 'Computer Science',
    specialization: 'Operating Systems',
    isOnline: true,
    tasksAssigned: 4,
    tasksCompleted: 27,
  },
  {
    id: 'fac-005',
    name: 'Dr. Lisa Johnson',
    email: 'lisa.johnson@gjust.edu.in',
    avatar: 'LJ',
    role: 'Assistant Professor',
    department: 'Computer Science',
    specialization: 'Computer Networks',
    isOnline: false,
    tasksAssigned: 7,
    tasksCompleted: 15,
  },
  {
    id: 'fac-006',
    name: 'Prof. Michael Brown',
    email: 'michael.brown@gjust.edu.in',
    avatar: 'MB',
    role: 'Guest Faculty',
    department: 'Computer Science',
    specialization: 'Web Development',
    isOnline: true,
    tasksAssigned: 3,
    tasksCompleted: 12,
  },
];

export const PROJECTS: Project[] = [
  { id: 'proj-1', name: 'Operating Systems', key: 'OS', color: '#3B82F6', description: 'OS Theory and Lab', taskCount: 24 },
  { id: 'proj-2', name: 'Database Systems', key: 'DBMS', color: '#10B981', description: 'DBMS Theory and Lab', taskCount: 18 },
  { id: 'proj-3', name: 'Machine Learning', key: 'ML', color: '#8B5CF6', description: 'ML Theory and Lab', taskCount: 12 },
  { id: 'proj-4', name: 'Academic Admin', key: 'ADM', description: 'Administrative Tasks', taskCount: 8 },
  { id: 'proj-5', name: 'Web Development', key: 'WEB', color: '#F59E0B', description: 'Web Tech Lab', taskCount: 15 },
  { id: 'proj-6', name: 'Computer Networks', key: 'CN', color: '#EC4899', description: 'CN Theory and Lab', taskCount: 10 },
];

export const COMMITTEES: Committee[] = [
  { id: 'comm-1', name: 'Academic Board', description: 'Curriculum and academic policies', memberCount: 8, activeTasks: 5 },
  { id: 'comm-2', name: 'Exam Committee', description: 'Examination planning and execution', memberCount: 6, activeTasks: 12 },
  { id: 'comm-3', name: 'Events Committee', description: 'Technical symposiums and events', memberCount: 5, activeTasks: 8 },
  { id: 'comm-4', name: 'Accreditation Team', description: 'NBA NAAC compliance', memberCount: 4, activeTasks: 15 },
  { id: 'comm-5', name: 'Research Committee', description: 'Research and publications', memberCount: 6, activeTasks: 3 },
];

export const ADMIN_TASKS: Task[] = [
  {
    id: 'ADM-001',
    type: 'task',
    title: 'Submit End Semester Question Papers',
    description: 'Prepare and submit question papers for Operating Systems and DBMS for the upcoming end semester examinations. Ensure proper formatting and mark distribution.',
    status: 'created',
    assignee: 'You',
    assigneeDetails: {
      id: 'fac-001',
      name: 'Dr. Sarah Chen',
      avatar: 'SC',
      role: 'HOD',
      assignedBy: 'Dr. Sarah Chen',
      assignedAt: new Date(Date.now() - 172800000),
    },
    dueDate: new Date(Date.now() + 172800000),
    priority: 'high',
    committee: 'Exam Committee',
    category: 'exam',
    createdAt: new Date(Date.now() - 172800000),
    updatedAt: new Date(),
    estimatedHours: 8,
  },
  {
    id: 'ADM-002',
    type: 'task',
    title: 'Complete Faculty Performance Review',
    description: 'Submit your annual performance review documents including student feedback analysis, research publications, and self-assessment.',
    status: 'in_progress',
    assignee: 'You',
    assigneeDetails: {
      id: 'fac-001',
      name: 'Dr. Sarah Chen',
      avatar: 'SC',
      role: 'HOD',
      assignedBy: 'Dr. Sarah Chen',
      assignedAt: new Date(Date.now() - 432000000),
    },
    dueDate: new Date(Date.now() + 432000000),
    priority: 'medium',
    committee: 'Academic Board',
    category: 'administrative',
    createdAt: new Date(Date.now() - 432000000),
    updatedAt: new Date(),
    estimatedHours: 4,
    comments: [
      {
        id: 'com-1',
        userId: 'fac-001',
        userName: 'Dr. Sarah Chen',
        userAvatar: 'SC',
        content: 'Please include your research publications from the past year.',
        createdAt: new Date(Date.now() - 86400000),
      }
    ]
  },
  {
    id: 'ADM-003',
    type: 'task',
    title: 'Update Course Materials for Cloud Computing',
    description: 'Upload latest lecture notes, lab manuals, and assignments for the new cloud computing module. Include practical exercises.',
    status: 'under_review',
    assignee: 'You',
    assigneeDetails: {
      id: 'fac-002',
      name: 'Prof. Rahul Kumar',
      avatar: 'RK',
      role: 'Senior Professor',
      assignedBy: 'Prof. Rahul Kumar',
      assignedAt: new Date(Date.now() - 259200000),
    },
    dueDate: new Date(Date.now() + 86400000),
    priority: 'high',
    committee: 'Curriculum',
    category: 'teaching',
    createdAt: new Date(Date.now() - 259200000),
    updatedAt: new Date(),
    estimatedHours: 6,
  },
  {
    id: 'ADM-004',
    type: 'task',
    title: 'Prepare NBA Documentation',
    description: 'Collect and organize course files, lab manuals, and assessment records for NBA accreditation visit scheduled next month.',
    status: 'created',
    assignee: 'You',
    assigneeDetails: {
      id: 'fac-001',
      name: 'Dr. Sarah Chen',
      avatar: 'SC',
      role: 'HOD',
      assignedBy: 'Dr. Sarah Chen',
      assignedAt: new Date(Date.now() - 86400000),
    },
    dueDate: new Date(Date.now() + 1209600000),
    priority: 'critical',
    committee: 'Accreditation Team',
    category: 'accreditation',
    createdAt: new Date(Date.now() - 86400000),
    updatedAt: new Date(),
    estimatedHours: 20,
    subtasks: [
      { id: 'sub-1', title: 'Collect course files', status: 'done' },
      { id: 'sub-2', title: 'Organize lab manuals', status: 'in_progress' },
      { id: 'sub-3', title: 'Prepare assessment records', status: 'pending' },
    ]
  },
];

export const PERSONAL_TASKS: Task[] = [
  {
    id: 'PERS-001',
    type: 'task',
    title: 'Grade Assignment 3 - DBMS',
    description: 'Evaluate and grade the submitted assignments for Database Management System, Section B. Provide detailed feedback.',
    status: 'in_progress',
    assignee: 'You',
    dueDate: new Date(Date.now() + 86400000),
    priority: 'high',
    committee: 'Teaching',
    category: 'teaching',
    createdAt: new Date(Date.now() - 604800000),
    updatedAt: new Date(),
    estimatedHours: 5,
    loggedHours: 2,
  },
  {
    id: 'PERS-002',
    type: 'task',
    title: 'Prepare Lecture - Machine Learning',
    description: 'Create slides and material for next week\'s ML introduction lecture. Include hands-on examples.',
    status: 'created',
    assignee: 'You',
    dueDate: new Date(Date.now() + 259200000),
    priority: 'medium',
    committee: 'Teaching',
    category: 'teaching',
    createdAt: new Date(),
    updatedAt: new Date(),
    estimatedHours: 3,
  },
  {
    id: 'PERS-003',
    type: 'task',
    title: 'Conduct Lab Session - OS Process Scheduling',
    description: 'Conduct and document the process scheduling lab session for OS practicals. Submit attendance and performance report.',
    status: 'done',
    assignee: 'You',
    dueDate: new Date(Date.now() - 86400000),
    priority: 'low',
    committee: 'Teaching',
    category: 'teaching',
    createdAt: new Date(Date.now() - 172800000),
    updatedAt: new Date(Date.now() - 86400000),
    estimatedHours: 2,
    loggedHours: 2,
  },
  {
    id: 'PERS-004',
    type: 'task',
    title: 'Review Research Paper Submissions',
    description: 'Review 3 research paper submissions for the International Journal of Computing.',
    status: 'created',
    assignee: 'You',
    dueDate: new Date(Date.now() + 604800000),
    priority: 'medium',
    committee: 'Research Committee',
    category: 'research',
    createdAt: new Date(),
    updatedAt: new Date(),
    estimatedHours: 10,
  },
  {
    id: 'PERS-005',
    type: 'task',
    title: 'Prepare Mid-Term Exam Questions',
    description: 'Create question paper for mid-term examination covering units 1-4.',
    status: 'in_progress',
    assignee: 'You',
    dueDate: new Date(Date.now() + 432000000),
    priority: 'high',
    committee: 'Exam Committee',
    category: 'exam',
    createdAt: new Date(Date.now() - 259200000),
    updatedAt: new Date(),
    estimatedHours: 6,
    loggedHours: 4,
  },
];

export const COLLAB_TASKS: Task[] = [
  {
    id: 'COLL-001',
    type: 'task',
    title: 'Review Curriculum Changes for Next Semester',
    description: 'Collaborate with HOD to review and approve proposed curriculum modifications for B.Tech CSE.',
    status: 'in_progress',
    assignee: 'Prof. Rahul Kumar',
    assigneeDetails: {
      id: 'fac-002',
      name: 'Prof. Rahul Kumar',
      avatar: 'RK',
      role: 'Senior Professor',
      assignedBy: 'Dr. Sarah Chen',
      assignedAt: new Date(Date.now() - 604800000),
    },
    dueDate: new Date(Date.now() + 604800000),
    priority: 'high',
    committee: 'Academic Board',
    category: 'administrative',
    createdAt: new Date(Date.now() - 604800000),
    updatedAt: new Date(),
    estimatedHours: 8,
    comments: [
      {
        id: 'com-2',
        userId: 'fac-001',
        userName: 'Dr. Sarah Chen',
        userAvatar: 'SC',
        content: 'Please review the proposed changes to the ML syllabus.',
        createdAt: new Date(Date.now() - 172800000),
      }
    ]
  },
  {
    id: 'COLL-002',
    type: 'task',
    title: 'Organize Technical Symposium 2026',
    description: 'Coordinate with faculty members to plan and execute the annual technical symposium. Set up committees and timelines.',
    status: 'created',
    assignee: 'Prof. Amit Patel',
    assigneeDetails: {
      id: 'fac-004',
      name: 'Prof. Amit Patel',
      avatar: 'AP',
      role: 'Associate Professor',
      assignedBy: 'Dr. Sarah Chen',
      assignedAt: new Date(),
    },
    dueDate: new Date(Date.now() + 2592000000),
    priority: 'medium',
    committee: 'Events Committee',
    category: 'events',
    createdAt: new Date(),
    updatedAt: new Date(),
    estimatedHours: 15,
    subtasks: [
      { id: 'sub-4', title: 'Form organizing committee', status: 'in_progress' },
      { id: 'sub-5', title: 'Set budget', status: 'pending' },
      { id: 'sub-6', title: 'Invite speakers', status: 'pending' },
    ]
  },
  {
    id: 'COLL-003',
    type: 'task',
    title: 'Guest Lecture Coordination - AI/ML',
    description: 'Coordinate with external speaker Dr. James Wilson from MIT for the upcoming guest lecture on AI/ML trends.',
    status: 'under_review',
    assignee: 'Dr. Emily Watson',
    assigneeDetails: {
      id: 'fac-003',
      name: 'Dr. Emily Watson',
      avatar: 'EW',
      role: 'Assistant Professor',
      assignedBy: 'Prof. Amit Patel',
      assignedAt: new Date(Date.now() - 432000000),
    },
    dueDate: new Date(Date.now() + 432000000),
    priority: 'medium',
    committee: 'Events Committee',
    category: 'events',
    createdAt: new Date(Date.now() - 432000000),
    updatedAt: new Date(),
    estimatedHours: 5,
    comments: [
      {
        id: 'com-3',
        userId: 'fac-004',
        userName: 'Prof. Amit Patel',
        userAvatar: 'AP',
        content: 'Please confirm the final date with the speaker.',
        createdAt: new Date(Date.now() - 86400000),
      }
    ]
  },
  {
    id: 'COLL-004',
    type: 'task',
    title: 'Lab Equipment Purchase Approval',
    description: 'Prepare proposal for new lab equipment purchase for the networking lab upgrade.',
    status: 'created',
    assignee: 'Dr. Lisa Johnson',
    assigneeDetails: {
      id: 'fac-005',
      name: 'Dr. Lisa Johnson',
      avatar: 'LJ',
      role: 'Assistant Professor',
      assignedBy: 'Dr. Sarah Chen',
      assignedAt: new Date(),
    },
    dueDate: new Date(Date.now() + 1209600000),
    priority: 'low',
    committee: 'Academic Board',
    category: 'administrative',
    createdAt: new Date(),
    updatedAt: new Date(),
    estimatedHours: 4,
  },
];

export const KANBAN_COLUMNS = [
  { id: 'created', label: 'To Do', color: '#5E6C84' },
  { id: 'in_progress', label: 'In Progress', color: '#0052CC' },
  { id: 'under_review', label: 'In Review', color: '#FFAB00' },
  { id: 'done', label: 'Done', color: '#36B37E' },
  { id: 'delayed', label: 'Delayed', color: '#FF5630' },
];

export const DASHBOARD_STATS = {
  totalTasks: 24,
  inProgress: 8,
  completed: 12,
  overdue: 2,
  pendingReview: 4,
  adminAssigned: 5,
  collabTasks: 4,
};

export const QUICK_ACTIONS = [
  { id: 'qa-1', label: 'Take Attendance', icon: 'ClipboardList', description: 'Open attendance session', color: '#3B82F6' },
  { id: 'qa-2', label: 'Create Assignment', icon: 'FileText', description: 'Post new assignment', color: '#10B981' },
  { id: 'qa-3', label: 'Enter Marks', icon: 'Award', description: 'Submit internal marks', color: '#8B5CF6' },
  { id: 'qa-4', label: 'Schedule Event', icon: 'Calendar', description: 'Create event/meeting', color: '#F59E0B' },
  { id: 'qa-5', label: 'Leave Request', icon: 'Clock', description: 'Submit leave application', color: '#EC4899' },
  { id: 'qa-6', label: 'Task Report', icon: 'BarChart3', description: 'View analytics', color: '#06B6D4' },
];
