export { default as OverviewTab } from './OverviewTab'
export { default as AssignmentsTab } from './AssignmentsTab'
export { default as AttendanceTab } from './AttendanceTab'
export { default as MarksTab } from './MarksTab'
export { default as TrackReportTab } from './TrackReportTab'
export { default as FeesTab } from './FeesTab'
export { default as HostelTab } from './HostelTab'
export { default as SportsTab } from './SportsTab'
export { default as RequestsTab } from './RequestsTab'
export { default as SettingsTab } from './SettingsTab'
export { default as Sidebar } from './Sidebar'
export * from './data'
